export const SET_TRACK_ORDER_DATA = 'SET_TRACK_ORDER_DATA';
export const SET_ID_VIEW = 'SET_ID_VIEW';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_TRACK_ORDER_PAGINATION = 'SET_TRACK_ORDER_PAGINATION';
export const SET_TRACK_ORDER_SEARCH_KEY = 'SET_TRACK_ORDER_SEARCH_KEY';
export const SET_TRACK_ORDER_DEFAULT_STATUS = 'SET_TRACK_ORDER_DEFAULT_STATUS';
export const SET_TRACK_ORDER_DETAIL_INFO = 'SET_TRACK_ORDER_DETAIL_INFO';

