export const TOGGLE_LANGUAGE = 'TOGGLE_LANGUAGE';
export const SET_PERMISSION = 'SET_PERMISSION';
export const SET_ACCOUNTINFO = 'SET_ACCOUNTINFO';
export const SET_PAGETITLE = 'SET_PAGETITLE';
export const SET_ORDER_USER = 'SET_ORDER_USER';
export const SET_GLOBAL_SETTING = 'SET_GLOBAL_SETTING';
export const GET_SETTING_BY_KEY = 'GET_SETTING_BY_KEY';
