// ui的state
export const SET_CART_COLLAPSE = 'SET_CART_COLLAPSE';
export const SET_PAGENATIONS = 'SET_PAGENATIONS';

export const SET_SEARCH_KEY = 'SET_SEARCH_KEY';

export const SET_GOODS = 'SET_GOODS';
export const SELECTING_GOODS_QUANTITY = 'SELECTING_GOODS_QUANTITY';

export const ADD_GOODS_TO_CART = 'ADD_GOODS_TO_CART';
export const DELETE_GOODS_FROM_CART = 'DELETE_GOODS_FROM_CART';
export const SET_CART_QUANTITY_GOODS = 'SET_CART_QUANTITY_GOODS';
export const EDITING_CART_GOODS = 'EDITING_CART_GOODS';
export const SET_CART_GOODS_PRICE = 'SET_CART_GOODS_PRICE';
export const RESET_ORDER = 'RESET_ORDER';
