export const SET_NEXT_BTN_AVALIABLE = 'SET_NEXT_BTN_AVALIABLE';
export const SET_PREVIOUS_BTN_AVALIABLE = 'SET_PREVIOUS_BTN_AVALIABLE';
export const SET_CURRENT_STEP = 'SET_CURRENT_STEP';
export const ADD_STEP = 'ADD_STEP';
