export const SET_USER_TABLE_DATA = 'SET_USER_TABLE_DATA';
export const SET_SEARCH_AREA_VISIBLE = 'SET_SEARCH_AREA_VISIBLE';
export const CHOOSE_USER_SET_PAGENATIONS = 'CHOOSE_USER_SET_PAGENATIONS';
export const CHOOSE_USER_SET_KEYS = 'CHOOSE_USER_SET_KEYS';
