export const SET_MARKETING_MATERIAL = 'SET_MARKETING_MATERIAL';
export const SET_MM_PAGINATION = 'SET_MM_PAGINATION';
export const SET_MM_LANGUAGE = 'SET_MM_LANGUAGE';
export const SET_MM_CATEGORY = 'SET_MM_CATEGORY';
