// ui的state
export const SET_ORDERS_BOARD_COLLAPSE = 'SET_ORDERS_BOARD_COLLAPSE';
export const SET_ORDER_COLLAPSE = 'SET_ORDER_COLLAPSE';
// goods
export const SELECTING_GOODS_QUANTITY = 'SELECTING_GOODS_QUANTITY';
export const ADD_GOODS_TO_ORDER = 'ADD_GOODS_TO_ORDER';
// order
export const SET_ORDER_STATUS = 'SET_ORDER_STATUS';
export const CREATE_ORDER = 'CREATE_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';

// order goods
export const DELETE_ORDER_GOODS = 'DELETE_ORDER_GOODS';
export const SET_ORDER_GOODS_QUANTITY = 'SET_ORDER_GOODS_QUANTITY';
