// ui的state
export const SO_SET_ORDERS_BOARD_COLLAPSE = 'SO_SET_ORDERS_BOARD_COLLAPSE';
export const SO_SET_ORDER_COLLAPSE = 'SO_SET_ORDER_COLLAPSE';
// goods
export const SO_SELECTING_GOODS_QUANTITY = 'SO_SELECTING_GOODS_QUANTITY';
export const SO_ADD_GOODS_TO_ORDER = 'SO_ADD_GOODS_TO_ORDER';
export const SO_UPDATE_GOODS_STATUS = 'SO_UPDATE_GOODS_STATUS';
// order
export const SO_SET_ORDER_STATUS = 'SO_SET_ORDER_STATUS';
export const SO_CREATE_ORDER = 'SO_CREATE_ORDER';
export const SO_DELETE_ORDER = 'SO_DELETE_ORDER';

// order goods
export const SO_DELETE_ORDER_GOODS = 'SO_DELETE_ORDER_GOODS';
export const SO_SET_ORDER_GOODS_QUANTITY = 'SO_SET_ORDER_GOODS_QUANTITY';
